language: c
sudo: true
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  matrix:
  - OCAML_VERSION=4.08 
  - OCAML_VERSION=4.08 DEPOPTS=graphics
  - OCAML_VERSION=4.08 DEPOPTS="graphics lablgtk"
  - OCAML_VERSION=4.09 
  - OCAML_VERSION=4.09 DEPOPTS=graphics 
  - OCAML_VERSION=4.09 DEPOPTS="graphics lablgtk"
  - OCAML_VERSION=4.10  
  - OCAML_VERSION=4.10 DEPOPTS=graphics 
  - OCAML_VERSION=4.10 DEPOPTS="graphics lablgtk"
os:
- linux